import localFont from "next/font/local";
import "./globals.css";


export const metadata = {
  title: "doc.ai development tracking",
  description: "Generated by Undisputed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
